services:
  db:
    image: postgres
    container_name: ex2-9-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=docker_course
      - POSTGRES_USER=irmindev
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    image: frontend-app
    build: ./frontend
    container_name: ex2-9-frontend

  backend:
    image: backend-app
    build: ./backend
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=docker_course
      - POSTGRES_USER=irmindev
      - POSTGRES_PASSWORD=123456
    container_name: ex2-9-backend

  cache:
    image: redis
    container_name: ex2-9-cache

  proxy:
    image: nginx
    container_name: ex2-8-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db-data: